### ISSUE TITLE
Codec/RPM/Types.hs: error: Ambiguous occurrence ‘<>’

### ISSUE THREAD

**Issue by juhp** [weldr/codec-rpm#31]
codec-rpm fails to build with ghc-8.4.2 in Stackage Nightly

```
Building library for codec-rpm-0.2.1..
[1 of 6] Compiling Codec.RPM.Internal.Numbers ( Codec/RPM/Internal/Numbers.hs, dist/build/Codec/RPM/Internal/Numbers.o )
[2 of 6] Compiling Codec.RPM.Tags   ( Codec/RPM/Tags.hs, dist/build/Codec/RPM/Tags.o )
[3 of 6] Compiling Codec.RPM.Types  ( Codec/RPM/Types.hs, dist/build/Codec/RPM/Types.o )

Codec/RPM/Types.hs:85:45: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at Codec/RPM/Types.hs:12:8-22
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.<>’,
                             imported from ‘Text.PrettyPrint’ at Codec/RPM/Types.hs:22:35-38
                             (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
   |
85 |                nest 2 $ text "rpmMajor:   " <> text (show rpmMajor),
   |                                             ^^

Codec/RPM/Types.hs:86:45: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at Codec/RPM/Types.hs:12:8-22
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.<>’,
                             imported from ‘Text.PrettyPrint’ at Codec/RPM/Types.hs:22:35-38
                             (and originally defined in ‘Text.PrettyPrint.HughesPJ’)
   |
86 |                nest 2 $ text "rpmMinor:   " <> text (show rpmMinor),
   |                                             ^^
:
:
```

**Comment by clumens** [comment]
This should be fixed now.  Thanks for the report.
